package com.lming.zhang.hospital.dao.model;

import java.io.Serializable;

public class ChcCorpInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.corp_id
     *
     * @mbg.generated
     */
    private String corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.corp_name
     *
     * @mbg.generated
     */
    private String corpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.business_code
     *
     * @mbg.generated
     */
    private String businessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.artificial_name
     *
     * @mbg.generated
     */
    private String artificialName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.id_card_no
     *
     * @mbg.generated
     */
    private String idCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.corp_phone
     *
     * @mbg.generated
     */
    private String corpPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.corp_logo
     *
     * @mbg.generated
     */
    private String corpLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.lat
     *
     * @mbg.generated
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.lng
     *
     * @mbg.generated
     */
    private String lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.corp_address
     *
     * @mbg.generated
     */
    private String corpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.expire_date
     *
     * @mbg.generated
     */
    private String expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.corp_status
     *
     * @mbg.generated
     */
    private String corpStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.open_status
     *
     * @mbg.generated
     */
    private String openStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_corp_info.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chc_corp_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.id
     *
     * @return the value of chc_corp_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.id
     *
     * @param id the value for chc_corp_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.corp_id
     *
     * @return the value of chc_corp_info.corp_id
     *
     * @mbg.generated
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.corp_id
     *
     * @param corpId the value for chc_corp_info.corp_id
     *
     * @mbg.generated
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId == null ? null : corpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.corp_name
     *
     * @return the value of chc_corp_info.corp_name
     *
     * @mbg.generated
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.corp_name
     *
     * @param corpName the value for chc_corp_info.corp_name
     *
     * @mbg.generated
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName == null ? null : corpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.business_code
     *
     * @return the value of chc_corp_info.business_code
     *
     * @mbg.generated
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.business_code
     *
     * @param businessCode the value for chc_corp_info.business_code
     *
     * @mbg.generated
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode == null ? null : businessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.artificial_name
     *
     * @return the value of chc_corp_info.artificial_name
     *
     * @mbg.generated
     */
    public String getArtificialName() {
        return artificialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.artificial_name
     *
     * @param artificialName the value for chc_corp_info.artificial_name
     *
     * @mbg.generated
     */
    public void setArtificialName(String artificialName) {
        this.artificialName = artificialName == null ? null : artificialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.id_card_no
     *
     * @return the value of chc_corp_info.id_card_no
     *
     * @mbg.generated
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.id_card_no
     *
     * @param idCardNo the value for chc_corp_info.id_card_no
     *
     * @mbg.generated
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.corp_phone
     *
     * @return the value of chc_corp_info.corp_phone
     *
     * @mbg.generated
     */
    public String getCorpPhone() {
        return corpPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.corp_phone
     *
     * @param corpPhone the value for chc_corp_info.corp_phone
     *
     * @mbg.generated
     */
    public void setCorpPhone(String corpPhone) {
        this.corpPhone = corpPhone == null ? null : corpPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.corp_logo
     *
     * @return the value of chc_corp_info.corp_logo
     *
     * @mbg.generated
     */
    public String getCorpLogo() {
        return corpLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.corp_logo
     *
     * @param corpLogo the value for chc_corp_info.corp_logo
     *
     * @mbg.generated
     */
    public void setCorpLogo(String corpLogo) {
        this.corpLogo = corpLogo == null ? null : corpLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.lat
     *
     * @return the value of chc_corp_info.lat
     *
     * @mbg.generated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.lat
     *
     * @param lat the value for chc_corp_info.lat
     *
     * @mbg.generated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.lng
     *
     * @return the value of chc_corp_info.lng
     *
     * @mbg.generated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.lng
     *
     * @param lng the value for chc_corp_info.lng
     *
     * @mbg.generated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.corp_address
     *
     * @return the value of chc_corp_info.corp_address
     *
     * @mbg.generated
     */
    public String getCorpAddress() {
        return corpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.corp_address
     *
     * @param corpAddress the value for chc_corp_info.corp_address
     *
     * @mbg.generated
     */
    public void setCorpAddress(String corpAddress) {
        this.corpAddress = corpAddress == null ? null : corpAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.expire_date
     *
     * @return the value of chc_corp_info.expire_date
     *
     * @mbg.generated
     */
    public String getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.expire_date
     *
     * @param expireDate the value for chc_corp_info.expire_date
     *
     * @mbg.generated
     */
    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate == null ? null : expireDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.corp_status
     *
     * @return the value of chc_corp_info.corp_status
     *
     * @mbg.generated
     */
    public String getCorpStatus() {
        return corpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.corp_status
     *
     * @param corpStatus the value for chc_corp_info.corp_status
     *
     * @mbg.generated
     */
    public void setCorpStatus(String corpStatus) {
        this.corpStatus = corpStatus == null ? null : corpStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.open_status
     *
     * @return the value of chc_corp_info.open_status
     *
     * @mbg.generated
     */
    public String getOpenStatus() {
        return openStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.open_status
     *
     * @param openStatus the value for chc_corp_info.open_status
     *
     * @mbg.generated
     */
    public void setOpenStatus(String openStatus) {
        this.openStatus = openStatus == null ? null : openStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_corp_info.desc
     *
     * @return the value of chc_corp_info.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_corp_info.desc
     *
     * @param desc the value for chc_corp_info.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}