package com.lming.zhang.hospital.dao.model;

import java.io.Serializable;

public class ChcCommunityHspl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_community_hspl.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_community_hspl.hspl_name
     *
     * @mbg.generated
     */
    private String hsplName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_community_hspl.hspl_phone
     *
     * @mbg.generated
     */
    private String hsplPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_community_hspl.work_begintime
     *
     * @mbg.generated
     */
    private String workBegintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_community_hspl.work_endtime
     *
     * @mbg.generated
     */
    private String workEndtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_community_hspl.business_code
     *
     * @mbg.generated
     */
    private String businessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_community_hspl.artifical_name
     *
     * @mbg.generated
     */
    private String artificalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_community_hspl.id_card_no
     *
     * @mbg.generated
     */
    private String idCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_community_hspl.hspl_address
     *
     * @mbg.generated
     */
    private String hsplAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_community_hspl.lat
     *
     * @mbg.generated
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_community_hspl.lng
     *
     * @mbg.generated
     */
    private String lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_community_hspl.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chc_community_hspl
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_community_hspl.id
     *
     * @return the value of chc_community_hspl.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_community_hspl.id
     *
     * @param id the value for chc_community_hspl.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_community_hspl.hspl_name
     *
     * @return the value of chc_community_hspl.hspl_name
     *
     * @mbg.generated
     */
    public String getHsplName() {
        return hsplName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_community_hspl.hspl_name
     *
     * @param hsplName the value for chc_community_hspl.hspl_name
     *
     * @mbg.generated
     */
    public void setHsplName(String hsplName) {
        this.hsplName = hsplName == null ? null : hsplName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_community_hspl.hspl_phone
     *
     * @return the value of chc_community_hspl.hspl_phone
     *
     * @mbg.generated
     */
    public String getHsplPhone() {
        return hsplPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_community_hspl.hspl_phone
     *
     * @param hsplPhone the value for chc_community_hspl.hspl_phone
     *
     * @mbg.generated
     */
    public void setHsplPhone(String hsplPhone) {
        this.hsplPhone = hsplPhone == null ? null : hsplPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_community_hspl.work_begintime
     *
     * @return the value of chc_community_hspl.work_begintime
     *
     * @mbg.generated
     */
    public String getWorkBegintime() {
        return workBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_community_hspl.work_begintime
     *
     * @param workBegintime the value for chc_community_hspl.work_begintime
     *
     * @mbg.generated
     */
    public void setWorkBegintime(String workBegintime) {
        this.workBegintime = workBegintime == null ? null : workBegintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_community_hspl.work_endtime
     *
     * @return the value of chc_community_hspl.work_endtime
     *
     * @mbg.generated
     */
    public String getWorkEndtime() {
        return workEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_community_hspl.work_endtime
     *
     * @param workEndtime the value for chc_community_hspl.work_endtime
     *
     * @mbg.generated
     */
    public void setWorkEndtime(String workEndtime) {
        this.workEndtime = workEndtime == null ? null : workEndtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_community_hspl.business_code
     *
     * @return the value of chc_community_hspl.business_code
     *
     * @mbg.generated
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_community_hspl.business_code
     *
     * @param businessCode the value for chc_community_hspl.business_code
     *
     * @mbg.generated
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode == null ? null : businessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_community_hspl.artifical_name
     *
     * @return the value of chc_community_hspl.artifical_name
     *
     * @mbg.generated
     */
    public String getArtificalName() {
        return artificalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_community_hspl.artifical_name
     *
     * @param artificalName the value for chc_community_hspl.artifical_name
     *
     * @mbg.generated
     */
    public void setArtificalName(String artificalName) {
        this.artificalName = artificalName == null ? null : artificalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_community_hspl.id_card_no
     *
     * @return the value of chc_community_hspl.id_card_no
     *
     * @mbg.generated
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_community_hspl.id_card_no
     *
     * @param idCardNo the value for chc_community_hspl.id_card_no
     *
     * @mbg.generated
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_community_hspl.hspl_address
     *
     * @return the value of chc_community_hspl.hspl_address
     *
     * @mbg.generated
     */
    public String getHsplAddress() {
        return hsplAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_community_hspl.hspl_address
     *
     * @param hsplAddress the value for chc_community_hspl.hspl_address
     *
     * @mbg.generated
     */
    public void setHsplAddress(String hsplAddress) {
        this.hsplAddress = hsplAddress == null ? null : hsplAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_community_hspl.lat
     *
     * @return the value of chc_community_hspl.lat
     *
     * @mbg.generated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_community_hspl.lat
     *
     * @param lat the value for chc_community_hspl.lat
     *
     * @mbg.generated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_community_hspl.lng
     *
     * @return the value of chc_community_hspl.lng
     *
     * @mbg.generated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_community_hspl.lng
     *
     * @param lng the value for chc_community_hspl.lng
     *
     * @mbg.generated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_community_hspl.user_id
     *
     * @return the value of chc_community_hspl.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_community_hspl.user_id
     *
     * @param userId the value for chc_community_hspl.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}