package com.lming.zhang.hospital.dao.model;

import java.io.Serializable;

public class ChcDoctorLevel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_level.level_id
     *
     * @mbg.generated
     */
    private Integer levelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_level.level_name
     *
     * @mbg.generated
     */
    private String levelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chc_doctor_level
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_level.level_id
     *
     * @return the value of chc_doctor_level.level_id
     *
     * @mbg.generated
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_level.level_id
     *
     * @param levelId the value for chc_doctor_level.level_id
     *
     * @mbg.generated
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_level.level_name
     *
     * @return the value of chc_doctor_level.level_name
     *
     * @mbg.generated
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_level.level_name
     *
     * @param levelName the value for chc_doctor_level.level_name
     *
     * @mbg.generated
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName == null ? null : levelName.trim();
    }
}