package com.lming.zhang.hospital.dao.model;

import java.io.Serializable;
import java.sql.Timestamp;

public class ChcDoctorInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.doctor_id
     *
     * @mbg.generated
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.id_card_no
     *
     * @mbg.generated
     */
    private String idCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.doctor_name
     *
     * @mbg.generated
     */
    private String doctorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.qafca_cert_no
     *
     * @mbg.generated
     */
    private String qafcaCertNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.qafca_cert_img
     *
     * @mbg.generated
     */
    private String qafcaCertImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.qafca_cert_sign_date
     *
     * @mbg.generated
     */
    private String qafcaCertSignDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.pract_cert_no
     *
     * @mbg.generated
     */
    private String practCertNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.pract_cert_img
     *
     * @mbg.generated
     */
    private String practCertImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.pract_cert_register_date
     *
     * @mbg.generated
     */
    private String practCertRegisterDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.hospital_id
     *
     * @mbg.generated
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.hospital_name
     *
     * @mbg.generated
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.subject_id
     *
     * @mbg.generated
     */
    private String subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.subject_name
     *
     * @mbg.generated
     */
    private String subjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.level_id
     *
     * @mbg.generated
     */
    private String levelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.level_name
     *
     * @mbg.generated
     */
    private String levelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.doctor_no
     *
     * @mbg.generated
     */
    private String doctorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.college_name
     *
     * @mbg.generated
     */
    private String collegeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.work_age
     *
     * @mbg.generated
     */
    private String workAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.fav_subject
     *
     * @mbg.generated
     */
    private String favSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.office_phone
     *
     * @mbg.generated
     */
    private String officePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.personal_phone
     *
     * @mbg.generated
     */
    private String personalPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.input_type
     *
     * @mbg.generated
     */
    private String inputType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.score
     *
     * @mbg.generated
     */
    private Float score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.create_time
     *
     * @mbg.generated
     */
    private Timestamp createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_doctor_info.update_time
     *
     * @mbg.generated
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chc_doctor_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.doctor_id
     *
     * @return the value of chc_doctor_info.doctor_id
     *
     * @mbg.generated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.doctor_id
     *
     * @param doctorId the value for chc_doctor_info.doctor_id
     *
     * @mbg.generated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.id_card_no
     *
     * @return the value of chc_doctor_info.id_card_no
     *
     * @mbg.generated
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.id_card_no
     *
     * @param idCardNo the value for chc_doctor_info.id_card_no
     *
     * @mbg.generated
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.user_id
     *
     * @return the value of chc_doctor_info.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.user_id
     *
     * @param userId the value for chc_doctor_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.doctor_name
     *
     * @return the value of chc_doctor_info.doctor_name
     *
     * @mbg.generated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.doctor_name
     *
     * @param doctorName the value for chc_doctor_info.doctor_name
     *
     * @mbg.generated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.sex
     *
     * @return the value of chc_doctor_info.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.sex
     *
     * @param sex the value for chc_doctor_info.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.birthday
     *
     * @return the value of chc_doctor_info.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.birthday
     *
     * @param birthday the value for chc_doctor_info.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.avatar
     *
     * @return the value of chc_doctor_info.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.avatar
     *
     * @param avatar the value for chc_doctor_info.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.qafca_cert_no
     *
     * @return the value of chc_doctor_info.qafca_cert_no
     *
     * @mbg.generated
     */
    public String getQafcaCertNo() {
        return qafcaCertNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.qafca_cert_no
     *
     * @param qafcaCertNo the value for chc_doctor_info.qafca_cert_no
     *
     * @mbg.generated
     */
    public void setQafcaCertNo(String qafcaCertNo) {
        this.qafcaCertNo = qafcaCertNo == null ? null : qafcaCertNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.qafca_cert_img
     *
     * @return the value of chc_doctor_info.qafca_cert_img
     *
     * @mbg.generated
     */
    public String getQafcaCertImg() {
        return qafcaCertImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.qafca_cert_img
     *
     * @param qafcaCertImg the value for chc_doctor_info.qafca_cert_img
     *
     * @mbg.generated
     */
    public void setQafcaCertImg(String qafcaCertImg) {
        this.qafcaCertImg = qafcaCertImg == null ? null : qafcaCertImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.qafca_cert_sign_date
     *
     * @return the value of chc_doctor_info.qafca_cert_sign_date
     *
     * @mbg.generated
     */
    public String getQafcaCertSignDate() {
        return qafcaCertSignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.qafca_cert_sign_date
     *
     * @param qafcaCertSignDate the value for chc_doctor_info.qafca_cert_sign_date
     *
     * @mbg.generated
     */
    public void setQafcaCertSignDate(String qafcaCertSignDate) {
        this.qafcaCertSignDate = qafcaCertSignDate == null ? null : qafcaCertSignDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.pract_cert_no
     *
     * @return the value of chc_doctor_info.pract_cert_no
     *
     * @mbg.generated
     */
    public String getPractCertNo() {
        return practCertNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.pract_cert_no
     *
     * @param practCertNo the value for chc_doctor_info.pract_cert_no
     *
     * @mbg.generated
     */
    public void setPractCertNo(String practCertNo) {
        this.practCertNo = practCertNo == null ? null : practCertNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.pract_cert_img
     *
     * @return the value of chc_doctor_info.pract_cert_img
     *
     * @mbg.generated
     */
    public String getPractCertImg() {
        return practCertImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.pract_cert_img
     *
     * @param practCertImg the value for chc_doctor_info.pract_cert_img
     *
     * @mbg.generated
     */
    public void setPractCertImg(String practCertImg) {
        this.practCertImg = practCertImg == null ? null : practCertImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.pract_cert_register_date
     *
     * @return the value of chc_doctor_info.pract_cert_register_date
     *
     * @mbg.generated
     */
    public String getPractCertRegisterDate() {
        return practCertRegisterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.pract_cert_register_date
     *
     * @param practCertRegisterDate the value for chc_doctor_info.pract_cert_register_date
     *
     * @mbg.generated
     */
    public void setPractCertRegisterDate(String practCertRegisterDate) {
        this.practCertRegisterDate = practCertRegisterDate == null ? null : practCertRegisterDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.hospital_id
     *
     * @return the value of chc_doctor_info.hospital_id
     *
     * @mbg.generated
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.hospital_id
     *
     * @param hospitalId the value for chc_doctor_info.hospital_id
     *
     * @mbg.generated
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.hospital_name
     *
     * @return the value of chc_doctor_info.hospital_name
     *
     * @mbg.generated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.hospital_name
     *
     * @param hospitalName the value for chc_doctor_info.hospital_name
     *
     * @mbg.generated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.subject_id
     *
     * @return the value of chc_doctor_info.subject_id
     *
     * @mbg.generated
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.subject_id
     *
     * @param subjectId the value for chc_doctor_info.subject_id
     *
     * @mbg.generated
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.subject_name
     *
     * @return the value of chc_doctor_info.subject_name
     *
     * @mbg.generated
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.subject_name
     *
     * @param subjectName the value for chc_doctor_info.subject_name
     *
     * @mbg.generated
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.level_id
     *
     * @return the value of chc_doctor_info.level_id
     *
     * @mbg.generated
     */
    public String getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.level_id
     *
     * @param levelId the value for chc_doctor_info.level_id
     *
     * @mbg.generated
     */
    public void setLevelId(String levelId) {
        this.levelId = levelId == null ? null : levelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.level_name
     *
     * @return the value of chc_doctor_info.level_name
     *
     * @mbg.generated
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.level_name
     *
     * @param levelName the value for chc_doctor_info.level_name
     *
     * @mbg.generated
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName == null ? null : levelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.doctor_no
     *
     * @return the value of chc_doctor_info.doctor_no
     *
     * @mbg.generated
     */
    public String getDoctorNo() {
        return doctorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.doctor_no
     *
     * @param doctorNo the value for chc_doctor_info.doctor_no
     *
     * @mbg.generated
     */
    public void setDoctorNo(String doctorNo) {
        this.doctorNo = doctorNo == null ? null : doctorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.college_name
     *
     * @return the value of chc_doctor_info.college_name
     *
     * @mbg.generated
     */
    public String getCollegeName() {
        return collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.college_name
     *
     * @param collegeName the value for chc_doctor_info.college_name
     *
     * @mbg.generated
     */
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName == null ? null : collegeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.work_age
     *
     * @return the value of chc_doctor_info.work_age
     *
     * @mbg.generated
     */
    public String getWorkAge() {
        return workAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.work_age
     *
     * @param workAge the value for chc_doctor_info.work_age
     *
     * @mbg.generated
     */
    public void setWorkAge(String workAge) {
        this.workAge = workAge == null ? null : workAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.fav_subject
     *
     * @return the value of chc_doctor_info.fav_subject
     *
     * @mbg.generated
     */
    public String getFavSubject() {
        return favSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.fav_subject
     *
     * @param favSubject the value for chc_doctor_info.fav_subject
     *
     * @mbg.generated
     */
    public void setFavSubject(String favSubject) {
        this.favSubject = favSubject == null ? null : favSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.office_phone
     *
     * @return the value of chc_doctor_info.office_phone
     *
     * @mbg.generated
     */
    public String getOfficePhone() {
        return officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.office_phone
     *
     * @param officePhone the value for chc_doctor_info.office_phone
     *
     * @mbg.generated
     */
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone == null ? null : officePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.personal_phone
     *
     * @return the value of chc_doctor_info.personal_phone
     *
     * @mbg.generated
     */
    public String getPersonalPhone() {
        return personalPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.personal_phone
     *
     * @param personalPhone the value for chc_doctor_info.personal_phone
     *
     * @mbg.generated
     */
    public void setPersonalPhone(String personalPhone) {
        this.personalPhone = personalPhone == null ? null : personalPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.status
     *
     * @return the value of chc_doctor_info.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.status
     *
     * @param status the value for chc_doctor_info.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.input_type
     *
     * @return the value of chc_doctor_info.input_type
     *
     * @mbg.generated
     */
    public String getInputType() {
        return inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.input_type
     *
     * @param inputType the value for chc_doctor_info.input_type
     *
     * @mbg.generated
     */
    public void setInputType(String inputType) {
        this.inputType = inputType == null ? null : inputType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.description
     *
     * @return the value of chc_doctor_info.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.description
     *
     * @param description the value for chc_doctor_info.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.score
     *
     * @return the value of chc_doctor_info.score
     *
     * @mbg.generated
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.score
     *
     * @param score the value for chc_doctor_info.score
     *
     * @mbg.generated
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.create_time
     *
     * @return the value of chc_doctor_info.create_time
     *
     * @mbg.generated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.create_time
     *
     * @param createTime the value for chc_doctor_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_doctor_info.update_time
     *
     * @return the value of chc_doctor_info.update_time
     *
     * @mbg.generated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_doctor_info.update_time
     *
     * @param updateTime the value for chc_doctor_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}