package com.lming.zhang.hospital.dao.model;

import java.io.Serializable;

public class ChcHospital implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_hospital.hospital_id
     *
     * @mbg.generated
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_hospital.hospital_name
     *
     * @mbg.generated
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_hospital.hospital_type
     *
     * @mbg.generated
     */
    private String hospitalType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_hospital.hospital_level
     *
     * @mbg.generated
     */
    private String hospitalLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_hospital.telnum
     *
     * @mbg.generated
     */
    private String telnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_hospital.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_hospital.lat
     *
     * @mbg.generated
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_hospital.lng
     *
     * @mbg.generated
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chc_hospital
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_hospital.hospital_id
     *
     * @return the value of chc_hospital.hospital_id
     *
     * @mbg.generated
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_hospital.hospital_id
     *
     * @param hospitalId the value for chc_hospital.hospital_id
     *
     * @mbg.generated
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_hospital.hospital_name
     *
     * @return the value of chc_hospital.hospital_name
     *
     * @mbg.generated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_hospital.hospital_name
     *
     * @param hospitalName the value for chc_hospital.hospital_name
     *
     * @mbg.generated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_hospital.hospital_type
     *
     * @return the value of chc_hospital.hospital_type
     *
     * @mbg.generated
     */
    public String getHospitalType() {
        return hospitalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_hospital.hospital_type
     *
     * @param hospitalType the value for chc_hospital.hospital_type
     *
     * @mbg.generated
     */
    public void setHospitalType(String hospitalType) {
        this.hospitalType = hospitalType == null ? null : hospitalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_hospital.hospital_level
     *
     * @return the value of chc_hospital.hospital_level
     *
     * @mbg.generated
     */
    public String getHospitalLevel() {
        return hospitalLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_hospital.hospital_level
     *
     * @param hospitalLevel the value for chc_hospital.hospital_level
     *
     * @mbg.generated
     */
    public void setHospitalLevel(String hospitalLevel) {
        this.hospitalLevel = hospitalLevel == null ? null : hospitalLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_hospital.telnum
     *
     * @return the value of chc_hospital.telnum
     *
     * @mbg.generated
     */
    public String getTelnum() {
        return telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_hospital.telnum
     *
     * @param telnum the value for chc_hospital.telnum
     *
     * @mbg.generated
     */
    public void setTelnum(String telnum) {
        this.telnum = telnum == null ? null : telnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_hospital.address
     *
     * @return the value of chc_hospital.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_hospital.address
     *
     * @param address the value for chc_hospital.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_hospital.lat
     *
     * @return the value of chc_hospital.lat
     *
     * @mbg.generated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_hospital.lat
     *
     * @param lat the value for chc_hospital.lat
     *
     * @mbg.generated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_hospital.lng
     *
     * @return the value of chc_hospital.lng
     *
     * @mbg.generated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_hospital.lng
     *
     * @param lng the value for chc_hospital.lng
     *
     * @mbg.generated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }
}