package com.lming.zhang.hospital.dao.model;

import java.io.Serializable;

public class ChcMobileNav implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_mobile_nav.nav_id
     *
     * @mbg.generated
     */
    private String navId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_mobile_nav.nav_name
     *
     * @mbg.generated
     */
    private String navName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_mobile_nav.link_url
     *
     * @mbg.generated
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_mobile_nav.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_mobile_nav.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chc_mobile_nav
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_mobile_nav.nav_id
     *
     * @return the value of chc_mobile_nav.nav_id
     *
     * @mbg.generated
     */
    public String getNavId() {
        return navId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_mobile_nav.nav_id
     *
     * @param navId the value for chc_mobile_nav.nav_id
     *
     * @mbg.generated
     */
    public void setNavId(String navId) {
        this.navId = navId == null ? null : navId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_mobile_nav.nav_name
     *
     * @return the value of chc_mobile_nav.nav_name
     *
     * @mbg.generated
     */
    public String getNavName() {
        return navName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_mobile_nav.nav_name
     *
     * @param navName the value for chc_mobile_nav.nav_name
     *
     * @mbg.generated
     */
    public void setNavName(String navName) {
        this.navName = navName == null ? null : navName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_mobile_nav.link_url
     *
     * @return the value of chc_mobile_nav.link_url
     *
     * @mbg.generated
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_mobile_nav.link_url
     *
     * @param linkUrl the value for chc_mobile_nav.link_url
     *
     * @mbg.generated
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_mobile_nav.icon
     *
     * @return the value of chc_mobile_nav.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_mobile_nav.icon
     *
     * @param icon the value for chc_mobile_nav.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_mobile_nav.sort
     *
     * @return the value of chc_mobile_nav.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_mobile_nav.sort
     *
     * @param sort the value for chc_mobile_nav.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}