package com.lming.zhang.hospital.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class ChcOrderMaster implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_order_master.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_order_master.reserve_id
     *
     * @mbg.generated
     */
    private String reserveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_order_master.from_userid
     *
     * @mbg.generated
     */
    private Integer fromUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_order_master.to_userid
     *
     * @mbg.generated
     */
    private Integer toUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_order_master.condition_description
     *
     * @mbg.generated
     */
    private String conditionDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_order_master.diagnosis_opinion
     *
     * @mbg.generated
     */
    private String diagnosisOpinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_order_master.attachment
     *
     * @mbg.generated
     */
    private String attachment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_order_master.signname
     *
     * @mbg.generated
     */
    private String signname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_order_master.orderAmt
     *
     * @mbg.generated
     */
    private BigDecimal orderamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_order_master.order_status
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_order_master.pay_status
     *
     * @mbg.generated
     */
    private String payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_order_master.next_id
     *
     * @mbg.generated
     */
    private String nextId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chc_order_master
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_order_master.order_id
     *
     * @return the value of chc_order_master.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_order_master.order_id
     *
     * @param orderId the value for chc_order_master.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_order_master.reserve_id
     *
     * @return the value of chc_order_master.reserve_id
     *
     * @mbg.generated
     */
    public String getReserveId() {
        return reserveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_order_master.reserve_id
     *
     * @param reserveId the value for chc_order_master.reserve_id
     *
     * @mbg.generated
     */
    public void setReserveId(String reserveId) {
        this.reserveId = reserveId == null ? null : reserveId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_order_master.from_userid
     *
     * @return the value of chc_order_master.from_userid
     *
     * @mbg.generated
     */
    public Integer getFromUserid() {
        return fromUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_order_master.from_userid
     *
     * @param fromUserid the value for chc_order_master.from_userid
     *
     * @mbg.generated
     */
    public void setFromUserid(Integer fromUserid) {
        this.fromUserid = fromUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_order_master.to_userid
     *
     * @return the value of chc_order_master.to_userid
     *
     * @mbg.generated
     */
    public Integer getToUserid() {
        return toUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_order_master.to_userid
     *
     * @param toUserid the value for chc_order_master.to_userid
     *
     * @mbg.generated
     */
    public void setToUserid(Integer toUserid) {
        this.toUserid = toUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_order_master.condition_description
     *
     * @return the value of chc_order_master.condition_description
     *
     * @mbg.generated
     */
    public String getConditionDescription() {
        return conditionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_order_master.condition_description
     *
     * @param conditionDescription the value for chc_order_master.condition_description
     *
     * @mbg.generated
     */
    public void setConditionDescription(String conditionDescription) {
        this.conditionDescription = conditionDescription == null ? null : conditionDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_order_master.diagnosis_opinion
     *
     * @return the value of chc_order_master.diagnosis_opinion
     *
     * @mbg.generated
     */
    public String getDiagnosisOpinion() {
        return diagnosisOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_order_master.diagnosis_opinion
     *
     * @param diagnosisOpinion the value for chc_order_master.diagnosis_opinion
     *
     * @mbg.generated
     */
    public void setDiagnosisOpinion(String diagnosisOpinion) {
        this.diagnosisOpinion = diagnosisOpinion == null ? null : diagnosisOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_order_master.attachment
     *
     * @return the value of chc_order_master.attachment
     *
     * @mbg.generated
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_order_master.attachment
     *
     * @param attachment the value for chc_order_master.attachment
     *
     * @mbg.generated
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_order_master.signname
     *
     * @return the value of chc_order_master.signname
     *
     * @mbg.generated
     */
    public String getSignname() {
        return signname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_order_master.signname
     *
     * @param signname the value for chc_order_master.signname
     *
     * @mbg.generated
     */
    public void setSignname(String signname) {
        this.signname = signname == null ? null : signname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_order_master.orderAmt
     *
     * @return the value of chc_order_master.orderAmt
     *
     * @mbg.generated
     */
    public BigDecimal getOrderamt() {
        return orderamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_order_master.orderAmt
     *
     * @param orderamt the value for chc_order_master.orderAmt
     *
     * @mbg.generated
     */
    public void setOrderamt(BigDecimal orderamt) {
        this.orderamt = orderamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_order_master.order_status
     *
     * @return the value of chc_order_master.order_status
     *
     * @mbg.generated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_order_master.order_status
     *
     * @param orderStatus the value for chc_order_master.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_order_master.pay_status
     *
     * @return the value of chc_order_master.pay_status
     *
     * @mbg.generated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_order_master.pay_status
     *
     * @param payStatus the value for chc_order_master.pay_status
     *
     * @mbg.generated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_order_master.next_id
     *
     * @return the value of chc_order_master.next_id
     *
     * @mbg.generated
     */
    public String getNextId() {
        return nextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_order_master.next_id
     *
     * @param nextId the value for chc_order_master.next_id
     *
     * @mbg.generated
     */
    public void setNextId(String nextId) {
        this.nextId = nextId == null ? null : nextId.trim();
    }
}