package com.lming.zhang.hospital.dao.model;

import java.io.Serializable;

public class ChcPlatNav implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_plat_nav.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_plat_nav.plat_type
     *
     * @mbg.generated
     */
    private String platType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_plat_nav.nav_id
     *
     * @mbg.generated
     */
    private String navId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chc_plat_nav
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_plat_nav.id
     *
     * @return the value of chc_plat_nav.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_plat_nav.id
     *
     * @param id the value for chc_plat_nav.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_plat_nav.plat_type
     *
     * @return the value of chc_plat_nav.plat_type
     *
     * @mbg.generated
     */
    public String getPlatType() {
        return platType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_plat_nav.plat_type
     *
     * @param platType the value for chc_plat_nav.plat_type
     *
     * @mbg.generated
     */
    public void setPlatType(String platType) {
        this.platType = platType == null ? null : platType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_plat_nav.nav_id
     *
     * @return the value of chc_plat_nav.nav_id
     *
     * @mbg.generated
     */
    public String getNavId() {
        return navId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_plat_nav.nav_id
     *
     * @param navId the value for chc_plat_nav.nav_id
     *
     * @mbg.generated
     */
    public void setNavId(String navId) {
        this.navId = navId == null ? null : navId.trim();
    }
}