package com.lming.zhang.hospital.dao.model;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

public class ChcReserve implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_reserve.reserve_id
     *
     * @mbg.generated
     */
    private String reserveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_reserve.from_userid
     *
     * @mbg.generated
     */
    private Integer fromUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_reserve.to_userid
     *
     * @mbg.generated
     */
    private Integer toUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_reserve.doctor_id
     *
     * @mbg.generated
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_reserve.create_time
     *
     * @mbg.generated
     */
    private Timestamp createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_reserve.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_reserve.reserve_time
     *
     * @mbg.generated
     */
    private String reserveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_reserve.reserve_date
     *
     * @mbg.generated
     */
    private Date reserveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_reserve.reserve_address
     *
     * @mbg.generated
     */
    private String reserveAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_reserve.lat
     *
     * @mbg.generated
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_reserve.lng
     *
     * @mbg.generated
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chc_reserve
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_reserve.reserve_id
     *
     * @return the value of chc_reserve.reserve_id
     *
     * @mbg.generated
     */
    public String getReserveId() {
        return reserveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_reserve.reserve_id
     *
     * @param reserveId the value for chc_reserve.reserve_id
     *
     * @mbg.generated
     */
    public void setReserveId(String reserveId) {
        this.reserveId = reserveId == null ? null : reserveId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_reserve.from_userid
     *
     * @return the value of chc_reserve.from_userid
     *
     * @mbg.generated
     */
    public Integer getFromUserid() {
        return fromUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_reserve.from_userid
     *
     * @param fromUserid the value for chc_reserve.from_userid
     *
     * @mbg.generated
     */
    public void setFromUserid(Integer fromUserid) {
        this.fromUserid = fromUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_reserve.to_userid
     *
     * @return the value of chc_reserve.to_userid
     *
     * @mbg.generated
     */
    public Integer getToUserid() {
        return toUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_reserve.to_userid
     *
     * @param toUserid the value for chc_reserve.to_userid
     *
     * @mbg.generated
     */
    public void setToUserid(Integer toUserid) {
        this.toUserid = toUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_reserve.doctor_id
     *
     * @return the value of chc_reserve.doctor_id
     *
     * @mbg.generated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_reserve.doctor_id
     *
     * @param doctorId the value for chc_reserve.doctor_id
     *
     * @mbg.generated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_reserve.create_time
     *
     * @return the value of chc_reserve.create_time
     *
     * @mbg.generated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_reserve.create_time
     *
     * @param createTime the value for chc_reserve.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_reserve.status
     *
     * @return the value of chc_reserve.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_reserve.status
     *
     * @param status the value for chc_reserve.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_reserve.reserve_time
     *
     * @return the value of chc_reserve.reserve_time
     *
     * @mbg.generated
     */
    public String getReserveTime() {
        return reserveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_reserve.reserve_time
     *
     * @param reserveTime the value for chc_reserve.reserve_time
     *
     * @mbg.generated
     */
    public void setReserveTime(String reserveTime) {
        this.reserveTime = reserveTime == null ? null : reserveTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_reserve.reserve_date
     *
     * @return the value of chc_reserve.reserve_date
     *
     * @mbg.generated
     */
    public Date getReserveDate() {
        return reserveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_reserve.reserve_date
     *
     * @param reserveDate the value for chc_reserve.reserve_date
     *
     * @mbg.generated
     */
    public void setReserveDate(Date reserveDate) {
        this.reserveDate = reserveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_reserve.reserve_address
     *
     * @return the value of chc_reserve.reserve_address
     *
     * @mbg.generated
     */
    public String getReserveAddress() {
        return reserveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_reserve.reserve_address
     *
     * @param reserveAddress the value for chc_reserve.reserve_address
     *
     * @mbg.generated
     */
    public void setReserveAddress(String reserveAddress) {
        this.reserveAddress = reserveAddress == null ? null : reserveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_reserve.lat
     *
     * @return the value of chc_reserve.lat
     *
     * @mbg.generated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_reserve.lat
     *
     * @param lat the value for chc_reserve.lat
     *
     * @mbg.generated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_reserve.lng
     *
     * @return the value of chc_reserve.lng
     *
     * @mbg.generated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_reserve.lng
     *
     * @param lng the value for chc_reserve.lng
     *
     * @mbg.generated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }
}