package com.lming.zhang.hospital.dao.model;

import java.io.Serializable;

public class ChcSubject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_subject.subject_id
     *
     * @mbg.generated
     */
    private String subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_subject.subject_name
     *
     * @mbg.generated
     */
    private String subjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chc_subject
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_subject.subject_id
     *
     * @return the value of chc_subject.subject_id
     *
     * @mbg.generated
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_subject.subject_id
     *
     * @param subjectId the value for chc_subject.subject_id
     *
     * @mbg.generated
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_subject.subject_name
     *
     * @return the value of chc_subject.subject_name
     *
     * @mbg.generated
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_subject.subject_name
     *
     * @param subjectName the value for chc_subject.subject_name
     *
     * @mbg.generated
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }
}