package com.lming.zhang.hospital.dao.model;

import java.io.Serializable;
import java.util.Date;

public class ChcTravelSchedule implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_travel_schedule.travel_id
     *
     * @mbg.generated
     */
    private Integer travelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_travel_schedule.doctor_id
     *
     * @mbg.generated
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_travel_schedule.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_travel_schedule.business_date
     *
     * @mbg.generated
     */
    private Date businessDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_travel_schedule.begin_time
     *
     * @mbg.generated
     */
    private String beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_travel_schedule.end_time
     *
     * @mbg.generated
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_travel_schedule.travel_address
     *
     * @mbg.generated
     */
    private String travelAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_travel_schedule.lat
     *
     * @mbg.generated
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_travel_schedule.lng
     *
     * @mbg.generated
     */
    private String lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_travel_schedule.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chc_travel_schedule
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_travel_schedule.travel_id
     *
     * @return the value of chc_travel_schedule.travel_id
     *
     * @mbg.generated
     */
    public Integer getTravelId() {
        return travelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_travel_schedule.travel_id
     *
     * @param travelId the value for chc_travel_schedule.travel_id
     *
     * @mbg.generated
     */
    public void setTravelId(Integer travelId) {
        this.travelId = travelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_travel_schedule.doctor_id
     *
     * @return the value of chc_travel_schedule.doctor_id
     *
     * @mbg.generated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_travel_schedule.doctor_id
     *
     * @param doctorId the value for chc_travel_schedule.doctor_id
     *
     * @mbg.generated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_travel_schedule.user_id
     *
     * @return the value of chc_travel_schedule.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_travel_schedule.user_id
     *
     * @param userId the value for chc_travel_schedule.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_travel_schedule.business_date
     *
     * @return the value of chc_travel_schedule.business_date
     *
     * @mbg.generated
     */
    public Date getBusinessDate() {
        return businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_travel_schedule.business_date
     *
     * @param businessDate the value for chc_travel_schedule.business_date
     *
     * @mbg.generated
     */
    public void setBusinessDate(Date businessDate) {
        this.businessDate = businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_travel_schedule.begin_time
     *
     * @return the value of chc_travel_schedule.begin_time
     *
     * @mbg.generated
     */
    public String getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_travel_schedule.begin_time
     *
     * @param beginTime the value for chc_travel_schedule.begin_time
     *
     * @mbg.generated
     */
    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime == null ? null : beginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_travel_schedule.end_time
     *
     * @return the value of chc_travel_schedule.end_time
     *
     * @mbg.generated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_travel_schedule.end_time
     *
     * @param endTime the value for chc_travel_schedule.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_travel_schedule.travel_address
     *
     * @return the value of chc_travel_schedule.travel_address
     *
     * @mbg.generated
     */
    public String getTravelAddress() {
        return travelAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_travel_schedule.travel_address
     *
     * @param travelAddress the value for chc_travel_schedule.travel_address
     *
     * @mbg.generated
     */
    public void setTravelAddress(String travelAddress) {
        this.travelAddress = travelAddress == null ? null : travelAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_travel_schedule.lat
     *
     * @return the value of chc_travel_schedule.lat
     *
     * @mbg.generated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_travel_schedule.lat
     *
     * @param lat the value for chc_travel_schedule.lat
     *
     * @mbg.generated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_travel_schedule.lng
     *
     * @return the value of chc_travel_schedule.lng
     *
     * @mbg.generated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_travel_schedule.lng
     *
     * @param lng the value for chc_travel_schedule.lng
     *
     * @mbg.generated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_travel_schedule.status
     *
     * @return the value of chc_travel_schedule.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_travel_schedule.status
     *
     * @param status the value for chc_travel_schedule.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}