package com.lming.zhang.hospital.dao.model;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

public class ChcUserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.login_name
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.login_pass
     *
     * @mbg.generated
     */
    private String loginPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.mobile_no
     *
     * @mbg.generated
     */
    private String mobileNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.usertype
     *
     * @mbg.generated
     */
    private String usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.user_status
     *
     * @mbg.generated
     */
    private String userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.login_count
     *
     * @mbg.generated
     */
    private Integer loginCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.last_login_ip
     *
     * @mbg.generated
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chc_user_info.update_time
     *
     * @mbg.generated
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chc_user_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.id
     *
     * @return the value of chc_user_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.id
     *
     * @param id the value for chc_user_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.openid
     *
     * @return the value of chc_user_info.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.openid
     *
     * @param openid the value for chc_user_info.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.login_name
     *
     * @return the value of chc_user_info.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.login_name
     *
     * @param loginName the value for chc_user_info.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.login_pass
     *
     * @return the value of chc_user_info.login_pass
     *
     * @mbg.generated
     */
    public String getLoginPass() {
        return loginPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.login_pass
     *
     * @param loginPass the value for chc_user_info.login_pass
     *
     * @mbg.generated
     */
    public void setLoginPass(String loginPass) {
        this.loginPass = loginPass == null ? null : loginPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.user_name
     *
     * @return the value of chc_user_info.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.user_name
     *
     * @param userName the value for chc_user_info.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.birthday
     *
     * @return the value of chc_user_info.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.birthday
     *
     * @param birthday the value for chc_user_info.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.mobile_no
     *
     * @return the value of chc_user_info.mobile_no
     *
     * @mbg.generated
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.mobile_no
     *
     * @param mobileNo the value for chc_user_info.mobile_no
     *
     * @mbg.generated
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.usertype
     *
     * @return the value of chc_user_info.usertype
     *
     * @mbg.generated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.usertype
     *
     * @param usertype the value for chc_user_info.usertype
     *
     * @mbg.generated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.role_id
     *
     * @return the value of chc_user_info.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.role_id
     *
     * @param roleId the value for chc_user_info.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.email
     *
     * @return the value of chc_user_info.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.email
     *
     * @param email the value for chc_user_info.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.user_status
     *
     * @return the value of chc_user_info.user_status
     *
     * @mbg.generated
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.user_status
     *
     * @param userStatus the value for chc_user_info.user_status
     *
     * @mbg.generated
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.login_count
     *
     * @return the value of chc_user_info.login_count
     *
     * @mbg.generated
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.login_count
     *
     * @param loginCount the value for chc_user_info.login_count
     *
     * @mbg.generated
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.last_login_ip
     *
     * @return the value of chc_user_info.last_login_ip
     *
     * @mbg.generated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.last_login_ip
     *
     * @param lastLoginIp the value for chc_user_info.last_login_ip
     *
     * @mbg.generated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chc_user_info.update_time
     *
     * @return the value of chc_user_info.update_time
     *
     * @mbg.generated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chc_user_info.update_time
     *
     * @param updateTime the value for chc_user_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}