server:
  port: 7001
  servlet:
    context-path: /upms
spring:
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    settings:
      template_update_delay: 0
  mvc:
    static-path-pattern: /static/**
  dubbo:
    name: upms-consumer
    address: zookeeper://127.0.0.1:2181







