package com.lming.zhang.hospital.dao.mapper;

import com.lming.zhang.hospital.dao.model.ChcCommunityHspl;
import com.lming.zhang.hospital.dao.model.ChcCommunityHsplExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChcCommunityHsplMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_community_hspl
     *
     * @mbg.generated
     */
    long countByExample(ChcCommunityHsplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_community_hspl
     *
     * @mbg.generated
     */
    int deleteByExample(ChcCommunityHsplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_community_hspl
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_community_hspl
     *
     * @mbg.generated
     */
    int insert(ChcCommunityHspl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_community_hspl
     *
     * @mbg.generated
     */
    int insertSelective(ChcCommunityHspl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_community_hspl
     *
     * @mbg.generated
     */
    List<ChcCommunityHspl> selectByExample(ChcCommunityHsplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_community_hspl
     *
     * @mbg.generated
     */
    ChcCommunityHspl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_community_hspl
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChcCommunityHspl record, @Param("example") ChcCommunityHsplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_community_hspl
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChcCommunityHspl record, @Param("example") ChcCommunityHsplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_community_hspl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChcCommunityHspl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_community_hspl
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChcCommunityHspl record);
}