package com.lming.zhang.hospital.dao.mapper;

import com.lming.zhang.hospital.dao.model.ChcCorpInfo;
import com.lming.zhang.hospital.dao.model.ChcCorpInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChcCorpInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_corp_info
     *
     * @mbg.generated
     */
    long countByExample(ChcCorpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_corp_info
     *
     * @mbg.generated
     */
    int deleteByExample(ChcCorpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_corp_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_corp_info
     *
     * @mbg.generated
     */
    int insert(ChcCorpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_corp_info
     *
     * @mbg.generated
     */
    int insertSelective(ChcCorpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_corp_info
     *
     * @mbg.generated
     */
    List<ChcCorpInfo> selectByExample(ChcCorpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_corp_info
     *
     * @mbg.generated
     */
    ChcCorpInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_corp_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChcCorpInfo record, @Param("example") ChcCorpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_corp_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChcCorpInfo record, @Param("example") ChcCorpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_corp_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChcCorpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_corp_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChcCorpInfo record);
}