package com.lming.zhang.hospital.dao.mapper;

import com.lming.zhang.hospital.dao.model.ChcDoctorInfo;
import com.lming.zhang.hospital.dao.model.ChcDoctorInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChcDoctorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_info
     *
     * @mbg.generated
     */
    long countByExample(ChcDoctorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_info
     *
     * @mbg.generated
     */
    int deleteByExample(ChcDoctorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("doctorId") Integer doctorId, @Param("idCardNo") String idCardNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_info
     *
     * @mbg.generated
     */
    int insert(ChcDoctorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_info
     *
     * @mbg.generated
     */
    int insertSelective(ChcDoctorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_info
     *
     * @mbg.generated
     */
    List<ChcDoctorInfo> selectByExample(ChcDoctorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_info
     *
     * @mbg.generated
     */
    ChcDoctorInfo selectByPrimaryKey(@Param("doctorId") Integer doctorId, @Param("idCardNo") String idCardNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChcDoctorInfo record, @Param("example") ChcDoctorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChcDoctorInfo record, @Param("example") ChcDoctorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChcDoctorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChcDoctorInfo record);
}