package com.lming.zhang.hospital.dao.mapper;

import com.lming.zhang.hospital.dao.model.ChcDoctorLevel;
import com.lming.zhang.hospital.dao.model.ChcDoctorLevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChcDoctorLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_level
     *
     * @mbg.generated
     */
    long countByExample(ChcDoctorLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_level
     *
     * @mbg.generated
     */
    int deleteByExample(ChcDoctorLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_level
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer levelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_level
     *
     * @mbg.generated
     */
    int insert(ChcDoctorLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_level
     *
     * @mbg.generated
     */
    int insertSelective(ChcDoctorLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_level
     *
     * @mbg.generated
     */
    List<ChcDoctorLevel> selectByExample(ChcDoctorLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_level
     *
     * @mbg.generated
     */
    ChcDoctorLevel selectByPrimaryKey(Integer levelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_level
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChcDoctorLevel record, @Param("example") ChcDoctorLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_level
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChcDoctorLevel record, @Param("example") ChcDoctorLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_level
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChcDoctorLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_doctor_level
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChcDoctorLevel record);
}