package com.lming.zhang.hospital.dao.mapper;

import com.lming.zhang.hospital.dao.model.ChcHospital;
import com.lming.zhang.hospital.dao.model.ChcHospitalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChcHospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_hospital
     *
     * @mbg.generated
     */
    long countByExample(ChcHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_hospital
     *
     * @mbg.generated
     */
    int deleteByExample(ChcHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_hospital
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer hospitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_hospital
     *
     * @mbg.generated
     */
    int insert(ChcHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_hospital
     *
     * @mbg.generated
     */
    int insertSelective(ChcHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_hospital
     *
     * @mbg.generated
     */
    List<ChcHospital> selectByExample(ChcHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_hospital
     *
     * @mbg.generated
     */
    ChcHospital selectByPrimaryKey(Integer hospitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_hospital
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChcHospital record, @Param("example") ChcHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_hospital
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChcHospital record, @Param("example") ChcHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_hospital
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChcHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_hospital
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChcHospital record);
}