package com.lming.zhang.hospital.dao.mapper;

import com.lming.zhang.hospital.dao.model.ChcMobileNav;
import com.lming.zhang.hospital.dao.model.ChcMobileNavExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChcMobileNavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_mobile_nav
     *
     * @mbg.generated
     */
    long countByExample(ChcMobileNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_mobile_nav
     *
     * @mbg.generated
     */
    int deleteByExample(ChcMobileNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_mobile_nav
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String navId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_mobile_nav
     *
     * @mbg.generated
     */
    int insert(ChcMobileNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_mobile_nav
     *
     * @mbg.generated
     */
    int insertSelective(ChcMobileNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_mobile_nav
     *
     * @mbg.generated
     */
    List<ChcMobileNav> selectByExample(ChcMobileNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_mobile_nav
     *
     * @mbg.generated
     */
    ChcMobileNav selectByPrimaryKey(String navId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_mobile_nav
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChcMobileNav record, @Param("example") ChcMobileNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_mobile_nav
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChcMobileNav record, @Param("example") ChcMobileNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_mobile_nav
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChcMobileNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_mobile_nav
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChcMobileNav record);
}