package com.lming.zhang.hospital.dao.mapper;

import com.lming.zhang.hospital.dao.model.ChcOrderDetail;
import com.lming.zhang.hospital.dao.model.ChcOrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChcOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_detail
     *
     * @mbg.generated
     */
    long countByExample(ChcOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_detail
     *
     * @mbg.generated
     */
    int deleteByExample(ChcOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_detail
     *
     * @mbg.generated
     */
    int insert(ChcOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_detail
     *
     * @mbg.generated
     */
    int insertSelective(ChcOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_detail
     *
     * @mbg.generated
     */
    List<ChcOrderDetail> selectByExample(ChcOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_detail
     *
     * @mbg.generated
     */
    ChcOrderDetail selectByPrimaryKey(String detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChcOrderDetail record, @Param("example") ChcOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChcOrderDetail record, @Param("example") ChcOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChcOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChcOrderDetail record);
}