package com.lming.zhang.hospital.dao.mapper;

import com.lming.zhang.hospital.dao.model.ChcOrderMaster;
import com.lming.zhang.hospital.dao.model.ChcOrderMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChcOrderMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_master
     *
     * @mbg.generated
     */
    long countByExample(ChcOrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_master
     *
     * @mbg.generated
     */
    int deleteByExample(ChcOrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_master
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_master
     *
     * @mbg.generated
     */
    int insert(ChcOrderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_master
     *
     * @mbg.generated
     */
    int insertSelective(ChcOrderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_master
     *
     * @mbg.generated
     */
    List<ChcOrderMaster> selectByExample(ChcOrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_master
     *
     * @mbg.generated
     */
    ChcOrderMaster selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_master
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChcOrderMaster record, @Param("example") ChcOrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_master
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChcOrderMaster record, @Param("example") ChcOrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChcOrderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_order_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChcOrderMaster record);
}