package com.lming.zhang.hospital.dao.mapper;

import com.lming.zhang.hospital.dao.model.ChcProductCategory;
import com.lming.zhang.hospital.dao.model.ChcProductCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChcProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_category
     *
     * @mbg.generated
     */
    long countByExample(ChcProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_category
     *
     * @mbg.generated
     */
    int deleteByExample(ChcProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_category
     *
     * @mbg.generated
     */
    int insert(ChcProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_category
     *
     * @mbg.generated
     */
    int insertSelective(ChcProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_category
     *
     * @mbg.generated
     */
    List<ChcProductCategory> selectByExample(ChcProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_category
     *
     * @mbg.generated
     */
    ChcProductCategory selectByPrimaryKey(String categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChcProductCategory record, @Param("example") ChcProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChcProductCategory record, @Param("example") ChcProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChcProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChcProductCategory record);
}