package com.lming.zhang.hospital.dao.mapper;

import com.lming.zhang.hospital.dao.model.ChcPlatNav;
import com.lming.zhang.hospital.dao.model.ChcPlatNavExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChcPlatNavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_plat_nav
     *
     * @mbg.generated
     */
    long countByExample(ChcPlatNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_plat_nav
     *
     * @mbg.generated
     */
    int deleteByExample(ChcPlatNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_plat_nav
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_plat_nav
     *
     * @mbg.generated
     */
    int insert(ChcPlatNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_plat_nav
     *
     * @mbg.generated
     */
    int insertSelective(ChcPlatNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_plat_nav
     *
     * @mbg.generated
     */
    List<ChcPlatNav> selectByExample(ChcPlatNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_plat_nav
     *
     * @mbg.generated
     */
    ChcPlatNav selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_plat_nav
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChcPlatNav record, @Param("example") ChcPlatNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_plat_nav
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChcPlatNav record, @Param("example") ChcPlatNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_plat_nav
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChcPlatNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_plat_nav
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChcPlatNav record);
}