package com.lming.zhang.hospital.dao.mapper;

import com.lming.zhang.hospital.dao.model.ChcProductKu;
import com.lming.zhang.hospital.dao.model.ChcProductKuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChcProductKuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_ku
     *
     * @mbg.generated
     */
    long countByExample(ChcProductKuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_ku
     *
     * @mbg.generated
     */
    int deleteByExample(ChcProductKuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_ku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("productId") String productId, @Param("productCode") String productCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_ku
     *
     * @mbg.generated
     */
    int insert(ChcProductKu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_ku
     *
     * @mbg.generated
     */
    int insertSelective(ChcProductKu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_ku
     *
     * @mbg.generated
     */
    List<ChcProductKu> selectByExample(ChcProductKuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_ku
     *
     * @mbg.generated
     */
    ChcProductKu selectByPrimaryKey(@Param("productId") String productId, @Param("productCode") String productCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_ku
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChcProductKu record, @Param("example") ChcProductKuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_ku
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChcProductKu record, @Param("example") ChcProductKuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_ku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChcProductKu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_product_ku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChcProductKu record);
}