package com.lming.zhang.hospital.dao.mapper;

import com.lming.zhang.hospital.dao.model.ChcReserve;
import com.lming.zhang.hospital.dao.model.ChcReserveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChcReserveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_reserve
     *
     * @mbg.generated
     */
    long countByExample(ChcReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_reserve
     *
     * @mbg.generated
     */
    int deleteByExample(ChcReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_reserve
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String reserveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_reserve
     *
     * @mbg.generated
     */
    int insert(ChcReserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_reserve
     *
     * @mbg.generated
     */
    int insertSelective(ChcReserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_reserve
     *
     * @mbg.generated
     */
    List<ChcReserve> selectByExample(ChcReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_reserve
     *
     * @mbg.generated
     */
    ChcReserve selectByPrimaryKey(String reserveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_reserve
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChcReserve record, @Param("example") ChcReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_reserve
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChcReserve record, @Param("example") ChcReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_reserve
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChcReserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_reserve
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChcReserve record);
}