package com.lming.zhang.hospital.dao.mapper;

import com.lming.zhang.hospital.dao.model.ChcTravelSchedule;
import com.lming.zhang.hospital.dao.model.ChcTravelScheduleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChcTravelScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_travel_schedule
     *
     * @mbg.generated
     */
    long countByExample(ChcTravelScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_travel_schedule
     *
     * @mbg.generated
     */
    int deleteByExample(ChcTravelScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_travel_schedule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer travelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_travel_schedule
     *
     * @mbg.generated
     */
    int insert(ChcTravelSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_travel_schedule
     *
     * @mbg.generated
     */
    int insertSelective(ChcTravelSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_travel_schedule
     *
     * @mbg.generated
     */
    List<ChcTravelSchedule> selectByExample(ChcTravelScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_travel_schedule
     *
     * @mbg.generated
     */
    ChcTravelSchedule selectByPrimaryKey(Integer travelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_travel_schedule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChcTravelSchedule record, @Param("example") ChcTravelScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_travel_schedule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChcTravelSchedule record, @Param("example") ChcTravelScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_travel_schedule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChcTravelSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chc_travel_schedule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChcTravelSchedule record);
}