server:
  port: 1111
spring:
  application:
    name: upms-service
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: hnboTAnExe
      url: jdbc:mysql://localhost:3306/chc?characterEncoding=utf-8&useSSL=false
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
# redis 单机
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
#    timeout: 0
#    jedis:
#      pool:
#        min-idle: 0
#        max-idle: 8
# dubbo
  dubbo:
    name: upms-provider
    port: 20881
    address: zookeeper://127.0.0.1:2181
# mybatis
mybatis:
  mapper-locations: classpath:com/lming/zhang/upms/dao/mapper/*.xml,com/lming/zhang/upms/rpc/dao/mapper/*.xml
  typeAliasesPackage: com.lming.zhang.upms.dao.model
  config-location: classpath:/config/mybatis-config.xml
  check-config-location: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





