server:
  port: 7001
spring:
  dubbo:
    name: dubbo-customer
    address: zookeeper://192.168.99.100:2181
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest



