server:
  port: 7001
spring:
  dubbo:
    name: dubbo-customer
    address: zookeeper://127.0.0.1:2181
#  rabbitmq:
#    host: 192.168.99.100
#    port: 5672
#    username: guest
#    password: guest
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: true



