server:
  port: 8888
  servlet:
    context-path: /hspl
spring:
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  mvc:
    static-path-pattern: /static/**
  dubbo:
      name: dubbo-customer
      address: zookeeper://127.0.0.1:2181