server:
  port: 7777
spring:
  application:
    name: hospital-service
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: hnboTAnExe
      url: jdbc:mysql://localhost:3306/chc?characterEncoding=utf-8&useSSL=false
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    pool:
      min-idle: 0
      max-idle: 8
# dubbo
  dubbo:
    name: dubbo-provider
    port: 20883
    address: zookeeper://127.0.0.1:2181
# rabbitMq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
# mybatis
mybatis:
  mapper-locations: classpath:com/lming/zhang/hospital/dao/mapper/*.xml
  typeAliasesPackage: com.lming.zhang.hospital.dao.model
  config-location: classpath:/config/mybatis-config.xml
  check-config-location: true
